/**
 * Live API table for component docs.
 * Data comes from `docs/api-data.json` (generated by `pnpm docs:api` / auto before doc).
 *
 * ```mdx
 * ## API
 * <ApiDocs name="Button" />
 * ```
 */
import { useLang } from '@rspress/core/runtime';
import apiData from './api-data.json';
import commonI18n from '../i18n/common.json';
import { hasCjk, toEnglishDemoText } from './api-locale';

type Lang = 'en' | 'zh';

type PropDoc = {
  name: string;
  required?: boolean;
  description?: string;
  type: { name: string };
  defaultValue?: { value?: string };
};

type ComponentDoc = {
  displayName?: string;
  description?: string;
  props?: Record<string, PropDoc>;
};

function tApi(key: keyof typeof commonI18n.api, lang: Lang) {
  return commonI18n.api[key]?.[lang] ?? commonI18n.api[key]?.en ?? key;
}

function propDesc(name: string, raw: string | undefined, lang: Lang) {
  const i18n =
    commonI18n.prop[name as keyof typeof commonI18n.prop]?.[lang] ??
    commonI18n.prop[name as keyof typeof commonI18n.prop]?.en;
  if (i18n) return i18n;
  if (!raw) return '-';
  if (lang === 'en' && hasCjk(raw)) {
    const localized = toEnglishDemoText(raw);
    return hasCjk(localized) ? '-' : localized;
  }
  return raw;
}

function softBreakType(typeName: string) {
  return String(typeName ?? '').replace(/([|&,])/g, '$1\u200B');
}

export interface ApiDocsProps {
  /** Component export name, e.g. `Button`. */
  name: string;
}

export function ApiDocs({ name }: ApiDocsProps) {
  const lang = (useLang() === 'zh' ? 'zh' : 'en') as Lang;
  const docs = (apiData as unknown as Record<string, ComponentDoc[] | null>)[name];

  if (!docs?.length) {
    return <p>{tApi('empty', lang)}</p>;
  }

  return (
    <div className="koi-api-docs space-y-8">
      {docs.map((doc) => {
        const props = doc.props ?? {};
        const rows = Object.keys(props)
          .sort((a, b) => {
            const aRequired = props[a]?.required ? 0 : 1;
            const bRequired = props[b]?.required ? 0 : 1;
            if (aRequired !== bRequired) return aRequired - bRequired;
            return a.localeCompare(b);
          })
          .map((propName) => {
            const prop = props[propName]!;
            const requiredLabel = tApi('required', lang);
            const typeText = softBreakType(prop.type.name);
            const rawDefault = prop.defaultValue?.value ?? '-';
            const defaultText =
              lang === 'en' ? toEnglishDemoText(rawDefault) : rawDefault;
            const desc = propDesc(prop.name, prop.description, lang);
            return (
              <tr key={prop.name}>
                <td>
                  <code>{prop.name}</code>
                </td>
                <td>{desc}</td>
                <td>
                  <code>{typeText}</code>
                  {prop.required ? (
                    <>
                      {' '}
                      <strong>({requiredLabel})</strong>
                    </>
                  ) : null}
                </td>
                <td>
                  <code>{defaultText}</code>
                </td>
              </tr>
            );
          });

        if (!rows.length) return null;

        let intro: string | null = null;
        if (doc.description) {
          const localized =
            lang === 'en'
              ? toEnglishDemoText(doc.description)
              : doc.description;
          if (!(lang === 'en' && hasCjk(localized))) intro = localized;
        }

        return (
          <div key={doc.displayName ?? name}>
            {doc.displayName ? <h3>{doc.displayName}</h3> : null}
            {intro ? <p>{intro}</p> : null}
            <table>
              <thead>
                <tr>
                  <th>{tApi('property', lang)}</th>
                  <th>{tApi('description', lang)}</th>
                  <th>{tApi('type', lang)}</th>
                  <th>{tApi('defaultValue', lang)}</th>
                </tr>
              </thead>
              <tbody>{rows}</tbody>
            </table>
          </div>
        );
      })}
    </div>
  );
}
