/** Component docs sidebar: category → ordered component names. */
export const CATEGORIES = {
  general: ['Button', 'Icon', 'Typography'],
  layout: [
    'Divider',
    'Grid',
    'Layout',
    'Space',
    'Flex',
    'Stack',
    'Box',
    'SafeArea',
  ],
  navigation: [
    'Affix',
    'Breadcrumb',
    'Dropdown',
    'Menu',
    'Pagination',
    'Steps',
    'Tabs',
    'NavBar',
    'TabBar',
    'IndexBar',
  ],
  dataEntry: [
    'AutoComplete',
    'Checkbox',
    'DatePicker',
    'Form',
    'Input',
    'InputNumber',
    'Radio',
    'Rate',
    'Select',
    'Slider',
    'Switch',
    'TextArea',
    'TimePicker',
    'Upload',
    'Cascader',
    'Picker',
    'SearchBar',
    'Stepper',
  ],
  dataDisplay: [
    'Avatar',
    'Badge',
    'Calendar',
    'Card',
    'Collapse',
    'Descriptions',
    'Empty',
    'Image',
    'List',
    'Popover',
    'Segmented',
    'Statistic',
    'Table',
    'Tag',
    'Timeline',
    'Tooltip',
    'Tree',
    'NoticeBar',
    'Swiper',
    'Ellipsis',
  ],
  feedback: [
    'Alert',
    'Drawer',
    'Modal',
    'Notification',
    'Popconfirm',
    'Progress',
    'Result',
    'Skeleton',
    'Spin',
    'Toast',
    'Popup',
    'ActionSheet',
    'Loading',
    'Mask',
    'Watermark',
  ],
  other: [
    'BackTop',
    'FloatButton',
    'PullToRefresh',
    'Footer',
    'FloatingPanel',
    'InfiniteScroll',
  ],
} as const;

/** Chinese display names for sidebar (zh locale). */
export const COMPONENT_ZH: Record<string, string> = {
  Button: '按钮',
  Icon: '图标',
  Typography: '排版',
  Divider: '分割线',
  Grid: '栅格',
  Layout: '布局',
  Space: '间距',
  Flex: '弹性布局',
  Stack: '堆叠',
  Box: '容器',
  SafeArea: '安全区',
  Affix: '固钉',
  Breadcrumb: '面包屑',
  Dropdown: '下拉菜单',
  Menu: '菜单',
  Pagination: '分页',
  Steps: '步骤条',
  Tabs: '标签页',
  NavBar: '导航栏',
  TabBar: '标签栏',
  IndexBar: '索引栏',
  AutoComplete: '自动完成',
  Checkbox: '多选框',
  DatePicker: '日期选择',
  Form: '表单',
  Input: '输入框',
  InputNumber: '数字输入',
  Radio: '单选框',
  Rate: '评分',
  Select: '选择器',
  Slider: '滑动输入',
  Switch: '开关',
  TextArea: '文本域',
  TimePicker: '时间选择',
  Upload: '上传',
  Cascader: '级联选择',
  Picker: '多列选择器',
  SearchBar: '搜索栏',
  Stepper: '步进器',
  Avatar: '头像',
  Badge: '徽标',
  Calendar: '日历',
  Card: '卡片',
  Collapse: '折叠面板',
  Descriptions: '描述列表',
  Empty: '空状态',
  Image: '图片',
  List: '列表',
  Popover: '气泡卡片',
  Segmented: '分段控制器',
  Statistic: '统计数值',
  Table: '表格',
  Tag: '标签',
  Timeline: '时间轴',
  Tooltip: '文字提示',
  Tree: '树形控件',
  NoticeBar: '通告栏',
  Swiper: '滑块视图',
  Ellipsis: '文本省略',
  Alert: '警告提示',
  Drawer: '抽屉',
  Modal: '对话框',
  Notification: '通知提醒',
  Popconfirm: '气泡确认',
  Progress: '进度条',
  Result: '结果',
  Skeleton: '骨架屏',
  Spin: '加载中',
  Toast: '轻提示',
  Popup: '弹出层',
  ActionSheet: '动作面板',
  Loading: '加载',
  Mask: '背景蒙层',
  Watermark: '水印',
  BackTop: '回到顶部',
  FloatButton: '悬浮按钮',
  PullToRefresh: '下拉刷新',
  Footer: '页脚',
  FloatingPanel: '浮动面板',
  InfiniteScroll: '无限滚动',
};

export const CATEGORY_LABELS = {
  general: { en: 'General', zh: '通用' },
  layout: { en: 'Layout', zh: '布局' },
  navigation: { en: 'Navigation', zh: '导航' },
  dataEntry: { en: 'Data entry', zh: '数据录入' },
  dataDisplay: { en: 'Data display', zh: '数据展示' },
  feedback: { en: 'Feedback', zh: '反馈' },
  other: { en: 'Other', zh: '其他' },
} as const;

export function allComponentNames(): string[] {
  return Object.values(CATEGORIES).flat();
}
